### ISSUE TITLE
Don't throw a 500 error if somebody looks up a non-existent Prismic article

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#7417]
If you visit this URL: <https://wellcomecollection.org/articles/yykk4hiaacqaqifn>

then you get an error form the application:

```
"GET /articles/yykk4hiaacqaqifn HTTP/1.1" 500 33489 "-" "Amazon CloudFront"
PrismicError: No documents were returned
at async fetchArticle (/app/content/webapp/.next/server/chunks/4472.js:26:20)
at async getServerSideProps (/app/content/webapp/.next/server/pages/article.js:187:27)
at async Object.renderToHTML (/app/node_modules/next/server/render.tsx:733:13)
at async doRender (/app/node_modules/next/server/next-server.ts:1669:27)
at async /app/node_modules/next/server/next-server.ts:1783:21
at async /app/node_modules/next/server/response-cache.ts:94:25 {
url: 'https://wellcomecollection.cdn.prismic.io/api/v2/documents/search?q=%5B%5Bat%28document.id%2C+%22yykk4hiaacqaqifn%22%29%5D%5D&fetchLinks=pages.title%2Cpages.promo%2Cevent-series.title%2Cevent-series.promo%2Cbooks.title%2Cbooks.promo%2Cevents.title%2Cevents.promo%2Carticles.title%2Carticles.promo%2Cexhibitions.title%2Cexhibitions.promo%2Cseries.title%2Cseries.promo%2Cwebcomic-series.title%2Cwebcomic-series.promo%2Carticle-formats.title%2Cpeople.name%2Cpeople.image%2Cpeople.description%2Cpeople.sameAs%2Cpeople.pronouns%2Corganisation.name%2Ceditorial-contributor-roles.title&ref=YakF_REAACIAc-l2&routes=%5B%7B%22type%22%3A%22seasons%22%2C%22path%22%3A%22%2Fseasons%2F%3Auid%22%7D%5D',
response: undefined
}
at Client.getFirst (/app/node_modules/prismic-client-beta/src/client.ts:471:9)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async Client.getByID (/app/node_modules/prismic-client-beta/src/client.ts:548:10)
```

The correct article URL is https://wellcomecollection.org/articles/YYKk4hIAACQAqiFN, but because Prismic IDs are case sensitive the lookup fails and we throw a 500 error. We should return a 404 instead.

**Comment by alexwlchan** [comment]
This got fixed at some point.
