### ISSUE TITLE
Fix a 500 error from the IIIF manifest for b12974821

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#7499]
See https://wellcomecollection.org/works/gc4zwh5h/items

This is the error we're getting at commit f6a432a:

```
TypeError: Cannot read property '0' of undefined
    at getServerSideProps (webpack-internal:///./pages/item.tsx:480:149)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Object.renderToHTML (./node_modules/next/server/render.tsx:733:13)
    at async doRender (./node_modules/next/server/next-server.ts:1669:27)
    at async ./node_modules/next/server/next-server.ts:1783:21
    at async ./node_modules/next/server/response-cache.ts:94:25
```

**Comment by alexwlchan** [comment]
Fixed.
