### ISSUE TITLE
Fix the 500 error from https://wellcomecollection.org/works/yxjy8j5f/items

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#7536]
https://wellcomecollection.org/works/yxjy8j5f/items

From the application logs:

```
"GET /works/yxjy8j5f/items HTTP/1.1" 500 33479 "-" "Amazon CloudFront"
TypeError: Cannot read property '0' of undefined
  at getServerSideProps (/app/catalogue/webapp/.next/server/pages/item.js:403:158)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async Object.renderToHTML (/app/node_modules/next/server/render.tsx:733:13)
  at async doRender (/app/node_modules/next/server/next-server.ts:1669:27)
  at async /app/node_modules/next/server/next-server.ts:1783:21
  at async /app/node_modules/next/server/response-cache.ts:94:25
```

**Comment by alexwlchan** [comment]
Fixed.
