### ISSUE TITLE
Inspect some IIIF viewer pages that have gone wrong

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#7628]
~404'ing https://wellcomecollection.org/works/yvqhmapu~

https://wellcomecollection.org/works/ts6fvee6/items
https://wellcomecollection.org/works/md65wwsf/items
https://wellcomecollection.org/works/kyutny8s/items

```
  TypeError: Cannot read properties of undefined (reading '0')
      at getServerSideProps (webpack-internal:///./pages/item.tsx:491:149)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.renderToHTML (/Users/alexwlchan/repos/dotorg/node_modules/next/server/render.tsx:733:13)
      at async doRender (/Users/alexwlchan/repos/dotorg/node_modules/next/server/next-server.ts:1669:27)
      at async /Users/alexwlchan/repos/dotorg/node_modules/next/server/next-server.ts:1783:21
      at async /Users/alexwlchan/repos/dotorg/node_modules/next/server/response-cache.ts:94:25
```

(I’ve just been looking through the app logs for the 500 errors over the weekend)

**Comment by alexwlchan** [comment]
https://wellcomecollection.org/works/d9gt6kwq/download?sierraId=b19651132

Notice that if you look at [the corresponding IIIF manifest](https://iiif.wellcomecollection.org/presentation/v2/b19651132), this intriguing line appears in the sequence list:

> Unsupported extension. This manifest is being used as a wrapper for non-IIIF content (e.g., audio, video) and is unfortunately incompatible with IIIF viewers.

**Comment by alexwlchan** [comment]
And also https://wellcomecollection.org/works/y4xrq2ux/download?sierraId=b20461069

**Comment by alexwlchan** [comment]
It looks like somebody has fixed those "Unsupported extension" errors – now they show you this:

<img width="445" alt="Screenshot 2022-02-25 at 08 07 22" src="https://user-images.githubusercontent.com/301220/155678585-59beb618-f3b6-458d-b483-7799d2037071.png">

🎉

**Comment by alexwlchan** [comment]
See https://wellcome.slack.com/archives/CN56BRQ5B/p1645389404477049 and https://wellcome.slack.com/archives/CN56BRQ5B/p1645389437740879

**Comment by alexwlchan** [comment]
https://wellcomecollection.org/works/pzmmhq3s/download?sierraId=b18846890

We don't display a viewer link on the page, but it's in the catalogue API with the following sequence:

> Unsupported extension. This manifest is being used as a wrapper for non-IIIF content (e.g., audio, video) and is unfortunately incompatible with IIIF viewers.

And people are getting linked to this page from Encore: https://search.wellcomelibrary.org/iii/encore/record/C__Rb1884689?lang=eng I suspect a class of these errors will become much rarer once we redirect Encore, because people will no longer be landing on these pages.

**Comment by alexwlchan** [comment]
These all seem to be fixed now. 🎉
