### ISSUE TITLE
Deal with the null errors in the front-end caused by missing server data

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/wellcomecollection.org#7954]
Every so often, we get a spate of 500 errors with the following error:

```
TypeError: Cannot read property 'data' of null
  at simplifyGlobalAlert (/app/catalogue/webapp/.next/server/chunks/651.js:47:15)
  at simplifyServerData (/app/catalogue/webapp/.next/server/chunks/651.js:38:20)
  at getServerData (/app/catalogue/webapp/.next/server/chunks/651.js:207:10)
```

That function isn't that complicated:

```typescript
function simplifyGlobalAlert(doc: GlobalAlertPrismicDocument): {
  data: InferDataInterface<GlobalAlertPrismicDocument>;
} {
  return { data: doc.data };
}
```

It looks like `doc` is null, which in this case comes from `serverData.prismic`. Presumably we're writing null values to the server data sometimes, and any requests to that task fail until it refreshes the data.

**Comment by alexwlchan** [comment]
I don't think we've seen this recently; closing.
